"""ADD CASCADE

Revision ID: 4a454fc103d3
Revises: a7a77d5b9849
Create Date: 2024-08-28 11:47:37.892650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a454fc103d3'
down_revision: Union[str, None] = 'a7a77d5b9849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FileLabelTable_ibfk_1', 'FileLabelTable', type_='foreignkey')
    op.drop_constraint('FileLabelTable_ibfk_2', 'FileLabelTable', type_='foreignkey')
    op.create_foreign_key(None, 'FileLabelTable', 'LabelTable', ['label_name'], ['label_name'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'FileLabelTable', 'FileTable', ['file_name'], ['file_name'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'FileLabelTable', type_='foreignkey')
    op.drop_constraint(None, 'FileLabelTable', type_='foreignkey')
    op.create_foreign_key('FileLabelTable_ibfk_2', 'FileLabelTable', 'LabelTable', ['label_name'], ['label_name'])
    op.create_foreign_key('FileLabelTable_ibfk_1', 'FileLabelTable', 'FileTable', ['file_name'], ['file_name'])
    # ### end Alembic commands ###
