"""test1

Revision ID: a7a77d5b9849
Revises: 
Create Date: 2024-08-27 18:04:29.269041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a7a77d5b9849'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LabelTable',
    sa.Column('label_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('creator', sa.String(length=50), nullable=True),
    sa.Column('creation_time', sa.DATETIME(), nullable=True),
    sa.Column('updater', sa.String(length=50), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('delete_time', sa.DATETIME(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('delete_people', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('label_name')
    )
    op.create_table('FileLabelTable',
    sa.Column('file_name', sa.String(length=50), nullable=False),
    sa.Column('label_name', sa.String(length=50), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['file_name'], ['FileTable.file_name'], ),
    sa.ForeignKeyConstraint(['label_name'], ['LabelTable.label_name'], ),
    sa.PrimaryKeyConstraint('file_name', 'label_name')
    )
    op.alter_column('FileTable', 'file_address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('FileTable', 'file_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('FileTable', 'download_number',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('FileTable', 'creator',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('FileTable', 'creation_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('User', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('User', 'privilege',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'privilege',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('User', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('FileTable', 'creation_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('FileTable', 'creator',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('FileTable', 'download_number',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('FileTable', 'file_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('FileTable', 'file_address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.drop_table('FileLabelTable')
    op.drop_table('LabelTable')
    # ### end Alembic commands ###
